export const API_URL = "http://localhost:8000/api"

//Product
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_PRODUCT_CATEGORY_ID = "GET_PRODUCT_CATEGORY_ID"
export const GET_PRODUCT_ID = "GET_PRODUCT_ID"
export const GET_PRODUCT_PAGINATION = "GET_PRODUCT_PAGINATION"

//Cart
export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_TO_CART = "UPDATE_TO_CART"
export const DELETE_TO_CART = "DELETE_TO_CART"
export const CART_COMPLETE = "CART_COMPLETE"

//User
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_USER = "GET_USER"
export const GET_ALL_USER = "GET_ALL_USER"
export const EDIT_USER = "EDIT_USER"

//Oder
export const ADD_BILL = 'ADD_BILL'
export const GET_ALL_BILL = 'GET_ALL_BILL'
export const GET_BILL_BY_CUSTOMER = 'GET_BILL_BY_CUSTOMER'
export const ADD_BILL_DETAIL = 'ADD_BILL_DETAIL'
export const GET_ALL_BILL_DETAIL = "GET_ALL_BILL_DETAIL"
export const GET_BILL_DETAIL_BY_ID_BILL = "GET_BILL_DETAIL_BY_ID_BILL"
export const GET_PURCHASE_HISTORY = "GET_PURCHASE_HISTORY"